[__config__]
oldver = "community-old-ver.json"
newver = "community-new-ver.json"
keyfile = "api-keys.toml"

[bitwarden]
source = "github"
github = "bitwarden/desktop"
use_latest_release = true
prefix = "v"

[bitwarden-cli]
source = "github"
github = "bitwarden/cli"
use_latest_release = true
prefix = "v"

[esh]
source = "github"
github = "jirutka/esh"
use_max_tag = true
prefix = "v"

[espeak-ng]
source = "github"
github = "espeak-ng/espeak-ng"
use_latest_release = true

[espeakup]
source = "github"
github = "linux-speakup/espeakup"
use_latest_release = true

[glulxe-term]
source = "github"
github = "erkyrath/glulxe"
use_latest_tag = true
prefix = "glulxe-"

[libglkterm]
source = "github"
github = "erkyrath/glkterm"
use_latest_tag = true
prefix = "glkterm-"

[lightdm-slick-greeter]
source = "github"
github = "linuxmint/slick-greeter"
use_latest_tag = true

[magic-wormhole]
source = "github"
github = "magic-wormhole/magic-wormhole"
use_latest_tag = true

[pcaudiolib]
source = "github"
github = "espeak-ng/pcaudiolib"
use_latest_release = true

[python-canonicaljson]
source = "github"
github = "matrix-org/python-canonicaljson"
use_latest_tag = true
prefix = "v"

[python-frozendict]
source = "pypi"
pypi = "frozendict"

[python-hkdf]
source = "pypi"
pypi = "hkdf"

[python-j2cli]
source = "github"
github = "kolypto/j2cli"
use_latest_tag = true
prefix = "v"

[python-magic-wormhole-mailbox-server]
source = "github"
github = "magic-wormhole/magic-wormhole-mailbox-server"
use_latest_tag = true

[python-magic-wormhole-transit-relay]
source = "github"
github = "magic-wormhole/magic-wormhole-transit-relay"
use_latest_tag = true

[python-signedjson]
source = "pypi"
pypi = "signedjson"

[python-spake2]
source = "github"
github = "warner/python-spake2"
use_latest_tag = true
prefix = "v"

[python-txtorcon]
source = "github"
github = "meejah/txtorcon"
use_latest_release = true
prefix = "v"

[repo]
source ="git"
git = "https://android.googlesource.com/tools/repo.git"
prefix = "v"

[rhvoice]
source = "github"
github = "rhvoice/rhvoice"
use_latest_release = true

[s3cmd]
source = "github"
github = "s3tools/s3cmd"
use_latest_release = true
prefix = "v"

[yadm]
source = "github"
github = "TheLocehiliosan/yadm"
use_latest_tag = true

[trash-cli]
source = "github"
github = "andreafrancia/trash-cli"
use_latest_tag = true
