[".config/zsh/functions/n"]
    type = "file"
    url = "https://raw.githubusercontent.com/jarun/nnn/master/misc/quitcd/quitcd.bash_sh_zsh"
[".config/zsh/.antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote"
